-- Step 1 - Add revenue column to order details table
-- This step adds a new column called 'revenue' to the northwind_order_details table. This column will be used to store the calculated revenue for each line item in the order details, which is derived from the unit price, quantity, and discount for each product in the order.

ALTER TABLE northwind_order_details
ADD COLUMN IF NOT EXISTS revenue DECIMAL(10, 2);

-- Step 2 - Update revenue column with calculated values
-- This step calculates the revenue for each line item in the northwind_order_details table by multiplying the unit price by the quantity and applying the discount. The calculated revenue is then stored in the newly added 'revenue' column for each record in the order details.

UPDATE northwind_order_details
SET revenue = unit_price * quantity * (1 - discount);

-- Step 3 - Calculate total revenue for each order
-- This query calculates the total revenue for each order by summing the revenue from the northwind_order_details table and grouping the results by order_id. The total revenue for each order is then ordered in descending order to identify the highest revenue-generating orders.

SELECT order_id, SUM(revenue) AS total_revenue
FROM northwind_order_details
GROUP BY order_id
ORDER BY total_revenue DESC;

-- Step 4 - Calculate total revenue for each customer
-- This query calculates the total revenue generated by each customer by joining the northwind_orders and northwind_order_details tables on the order_id. The total revenue for each customer is then grouped by customer_id and ordered in descending order to identify the highest revenue-generating customers.

SELECT northwind_orders.customer_id as customer_id, SUM(northwind_order_details.revenue) as revenue FROM northwind_orders
LEFT JOIN northwind_order_details
ON northwind_order_details.order_id = northwind_orders.order_id
GROUP BY customer_id
ORDER BY revenue DESC;

-- Step 5 - Calculate total revenue for each employee
-- This query calculates the total revenue generated by each employee by joining the northwind_orders and northwind_order_details tables on the order_id. The total revenue for each employee is then grouped by employee_id and ordered in descending order to identify the highest revenue-generating employees.

SELECT northwind_orders.employee_id as employee_id, SUM(northwind_order_details.revenue) as revenue FROM northwind_orders
LEFT JOIN northwind_order_details
ON northwind_order_details.order_id = northwind_orders.order_id
GROUP BY employee_id
ORDER BY revenue DESC;

-- Step 6 - Calculate total revenue for each product
-- This query calculates the total revenue generated by each product by grouping the northwind_order_details table by product_id and summing the revenue for each product. The results are then ordered in descending order to identify the highest revenue-generating products.

SELECT northwind_order_details.product_id as product_id, SUM(northwind_order_details.revenue) as revenue FROM northwind_order_details
GROUP BY product_id
ORDER BY revenue DESC;

-- Step 7 - Calculate top 5 orders, products, customers, and employees by revenue
-- This step identifies the top 5 orders, products, customers, and employees based on the total revenue generated. The queries calculate the total revenue for each order, product, customer, and employee, and then order the results in descending order to retrieve the top 5 entries for each category.

SELECT order_id, SUM(revenue) AS total_revenue
FROM northwind_order_details
GROUP BY order_id
ORDER BY total_revenue DESC
LIMIT 5;

SELECT product_id, SUM(revenue) AS total_revenue
FROM northwind_order_details
GROUP BY product_id
ORDER BY total_revenue DESC
LIMIT 5;

SELECT northwind_orders.customer_id as customer_id, SUM(northwind_order_details.revenue) as revenue FROM northwind_orders
LEFT JOIN northwind_order_details
ON northwind_order_details.order_id = northwind_orders.order_id
GROUP BY customer_id
ORDER BY revenue DESC
LIMIT 5;

SELECT northwind_orders.employee_id as employee_id, SUM(northwind_order_details.revenue) as revenue FROM northwind_orders
LEFT JOIN northwind_order_details
ON northwind_order_details.order_id = northwind_orders.order_id
GROUP BY employee_id
ORDER BY revenue DESC
LIMIT 5;

-- Step 8 - Calculate overall revenue metrics
-- This query calculates overall revenue metrics such as total orders, total revenue, average order revenue, minimum order revenue, and maximum order revenue by aggregating the data from the northwind_order_details table. These metrics provide insights into the overall performance of the business in terms of revenue generation.

SELECT
    COUNT(*) AS total_orders,
    SUM(order_revenue) AS total_revenue,
    AVG(order_revenue) AS avg_order_revenue,
    MIN(order_revenue) AS min_order_revenue,
    MAX(order_revenue) AS max_order_revenue
FROM (
    SELECT
        order_id,
        SUM(revenue) AS order_revenue
    FROM northwind_order_details
    GROUP BY order_id
) t;

